app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('akatsukiview.index');
});


Route::get('testJquery', function () {
    return view('testviewjquery');
});


Route::resource('isitabel','akatsukiController');

app/User.php
 <?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/akatsuki_tables.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class akatsuki_tables extends Model
{
	protected $table = 'akatsuki_tables';
    public $timestamps = true;
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/akatsukiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Log;
use App\Http\Requests;
use App\akatsuki_tables;

class akatsukiController extends Controller
{
    public function index()
    {
    	$isiTable = akatsuki_tables::get();
    	//return $isiTable;
        log::info("hellow");
    	return view('akatsukiView.index')->with('alldata',$isiTable);
    }


    public function create()
    {
    	return view('akatsukiView.create');
    }

    public function store(Request $req)
    {
    	//dd($req);
    	
    	$data = new akatsuki_tables;

    	$data->Name = $req->Name;
    	$data->Position = $req->Position;
    	$data->Secret_Jutsu = $req->Secret_Jutsu;
    	$data->Parner = $req->Parner;

    	$data->save();
    	

    	
		//	cara lain :
		//	$Input = $req->all();
		//	$data = akatsuki_tables::Create($Input);
    	

    	//return redirect()->route('akatsukiView.index');
		//	return "something";
		return redirect()->action('akatsukiController@index');
    }









    public function show($id)
    {
    	//return $id;
    	$datas = akatsuki_tables::find($id);
    	//return $data;

    	return view('akatsukiView.show')->with('showdata',$datas);
    }


public function edit($id)
{

    $datas = akatsuki_tables::find($id);
    //$test = akatsuki_tables::where("id",id)->first();
    //return $datas;
    return view('akatsukiView.edit')->with('input',$datas);;//,compact('input',$datas));//compact for single variable only

}


public function update(Request $req, $id)
{
    //dd($req);
    $data = akatsuki_tables::find($id);
    $data->name = $req->name;
    $data->position = $req->position;
    $data->secret_jutsu = $req->secret_jutsu;
    $data->parner = $req->parner;

    $data->save();
    return redirect()->action('akatsukiController@index');
}

public function delete($id)
{

}

public function destroy($id)
{
    	//akatsuki_tables::destroy($id);
    //dd($id);
    $pro=akatsuki_tables::where("id", $id)->first()->delete();
    //dd($pro);
    return redirect()->action('akatsukiController@index');
}


}

app/Http/Controllers/databaseConnection.php
<?php
define('host', 'localhost');
define('user', 'root');
define('password', 'croopside91');
define('dbname', 'crud');

function openConnection()
{
	mysql_select_db(dbname, mysql_connect(host, user, password));
}

function closeConnection()
{
	mysql_close(mysql_connect(host, user, password));
}
?>

resources/views/akatsukiView/create.blade.php
@extends('masterview.masterpage')

@section('title') Create Page
@stop


@section('body') This is Body of Create Page
	{!!Form::open(['route' => 'isitabel.store'])!!}
		{!!Form::label('name','Name')!!}
		{!!Form::text('Name', null, ['placeholder' => "Enter your name"])!!} <br/>
		{!!Form::label('posLabel','Position')!!}
		{!!Form::text('Position')!!} <br/>
		{!!Form::label('secLabel','Secret Jutsu')!!}
		{!!Form::text('Secret_Jutsu')!!} <br/>
		{!!Form::label('partLabel','Partners')!!}
		{!!Form::text('Parner')!!} <br/> <br/>
		{!!Form::submit('Add to DB')!!}
		

 	{!!Form::close()!!}
@stop

resources/views/akatsukiView/edit.blade.php
@extends('masterview.masterpage')

@section('title') Edit Page
@stop


@section('body') This is Body of Edit Page
	  {!!Form::model($input,[
		'method' => 'patch',
		'route' => ['isitabel.update',$input->id]])!!}
		{!!Form::label('name','Name')!!}
		{!!Form::text('name', $input->name, ['placeholder' => "Enter your name"])!!} <br/>
		{!!Form::label('posLabel','Position')!!}
		{!!Form::text('position',$input->position,['placeholder' => "Enter Position"])!!} <br/>
		{!!Form::label('secLabel','Secret Jutsu')!!}
		{!!Form::text('secret_jutsu',$input->secret_jutsu,['placeholder' => "Enter secret jutsu"])!!} <br/>
		{!!Form::label('partLabel','Partners')!!}
		{!!Form::text('parner', $input->parner,['placeholder' => "Enter the partner..."])!!} <br/> <br/>
		{!!Form::submit('Edit')!!}
		

 	{!!Form::close()!!}
@stop

resources/views/akatsukiView/index.blade.php
@extends('masterview.masterpage')

@section('title') Main Akatsuki Page 
@stop


@section('body') Main Akatsuki Body in index.blade

<h2> isi akatsuki_tables : </h2>
 <?php $index = 0; ?>
	@foreach($alldata as $data)
		<?php $index++; ?>
		No : {{$index++}} <br/>
		Id : {{$data->id}} <br/>
		Name : {{$data->name}} <br/>
		Position : {{$data->position}} <br/>
		Secret Jutsu : {{$data->secret_jutsu}} <br/>
		Partner : {{$data->parner}} <br/>
	***************************************************	<br/>
	@endforeach
 
@stop

resources/views/akatsukiView/show.blade.php
@extends('masterview.masterpage')

@section('title') Show Page
@stop


@section('body') This is Body of Show Page <br/>
	{!!Form::open([
		'method' => 'delete',
		'route'=>['isitabel.destroy', $showdata->id]
		])!!}
        Name : {{$showdata->name}} <br/>
		Position : {{$showdata->position}} <br/>
		Secret Jutsu : {{$showdata->secret_jutsu}} <br/>
		Partner : {{$showdata->parner}} <br/><br/>
		{!!Form::submit('Delete')!!}
       <a href="{{route('isitabel.edit',$showdata->id)}}">Edit </a>    
    {!!Form::close()!!}

@stop

resources/views/masterview/masterpage.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>@yield('title')</title>
</head>

<body>
    @include('masterview.menupage')
	@yield('body')
</body>

</html>

resources/views/masterview/menupage.blade.php
<h1> This is Hisoka Awesome Menu </h1>

<ul>
<li> Akatsuki Home </li>
<li> Akatsuki Members </li>
<li> Akatsuki Missions </li>

</ul>

resources/views/testviewjquery.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>
        <script type="text/javascript" src="jquery-1.8.3.min.js"></script>
        <script type="text/javascript" src="hisokajquery.js"></script>
    </head>
  <body>
  	<?php echo "Hellow Hisoka" ;

  	?>

  	<div id="test"> testajjah </div>
  </body>


  </html>